name: CI/CD Pipeline

on:
  push:
    paths:
      - 'src/**' #backend
      - 'frontend/squadgame-web-ui/squadgame-web-ui/**' #frontend
      - '.github/**'
    branches:
      - main

jobs:
  # Frontend Build and Test
  frontend:
    name: Build and Test React Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install
        working-directory: ./frontend/squadgame-web-ui/squadgame-web-ui

      - name: Run Tests
        run: npm test
        working-directory: ./frontend/squadgame-web-ui/squadgame-web-ui

      - name: Build Frontend
        run: npm run build
        working-directory: ./frontend/squadgame-web-ui/squadgame-web-ui

      - name: Upload Frontend Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: frontend-build
          path: ./frontend/squadgame-web-ui/squadgame-web-ui/build

  # Backend Build and Test
  backend:
    name: Build and Test .NET Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore ./src

      - name: Build Backend
        run: dotnet build --no-restore ./src

      - name: Run Tests
        run: dotnet test --no-build ./src

      - name: Upload Backend Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backend-build
          path: ./src/bin/Release/net8.0

  # Deployment to Azure
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Frontend Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: frontend-build

      - name: Download Backend Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: backend-build

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_AZURE_APP_NAME> # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./frontend/squadgame-web-ui/squadgame-web-ui/build # Deploy frontend
      - name: Deploy Backend
        uses: azure/webapps-deploy@v2
        with:
          app-name: <YOUR_AZURE_BACKEND_APP_NAME> # Replace with your Azure backend app name
          publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
          package: ./src/bin/Release/net8.0 # Deploy backend
